# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.overridePathCheck=true

# Kotlin Multiplatform
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

# Compose
org.jetbrains.compose.experimental.macos.enabled=false
