# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.overridePathCheck=true

# Kotlin Multiplatform
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

# Compose
org.jetbrains.compose.experimental.macos.enabled=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
